#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))

require 'yaml'
require 'pathname'

require 'bosh/director'
require 'tmux/client'

def die(msg)
  warn "Error: #{msg}"
  exit(1)
end

config = YAML.load_file(Pathname('~/.bosh_config').expand_path)

director_url = config['target'] # e.g. https://192.168.50.4:25555
director_auth = config['auth'][director_url] # username + password
deployment = ARGV.first || die('Missing argument for deployment name')

director = BOSH::Director.new(director_url,
                   director_auth['username'],
                   director_auth['password'],
                   verify_ssl: :none)

client = TMux::Client.new
session_name = "bosh-#{deployment}"

if client.session?(session_name)
  die 'Not creating new windows because there already is an existing tmux ' \
      "session named #{session_name}. Consider nuking it with:\n" \
      "tmux kill-session -t #{session_name}"
end

director.vms(deployment).each.with_index do |vm, window_index|
  window_name = "#{vm['job']}/#{vm['index']}"

  # tmux has no way to create a session without an initial window, so we have
  # to provide the command for the first window when creating the session.
  if window_index.zero?
    # client.create_session(session_name, window_name)
    `tmux new-session -d -s #{session_name} -n #{window_name} bosh ssh #{vm['job']}/#{vm['index']}`
  else
    # pane_0 = session.create_window(window_name)
    `tmux new-window -d -t #{session_name}: -n #{window_name} bosh ssh #{vm['job']}/#{vm['index']}`
  end

  # window.type('sudo su -', 'cd /var/vcap')
  `tmux send-keys -t #{session_name}:#{window_name} "sudo su -" C-m`
  `tmux send-keys -t #{session_name}:#{window_name} "cd /var/vcap" C-m`

  # split off the monit pane

  # pane_1 = pane_0.split('monit summary')
  width = 50 # characters
  `tmux split-window -d -h -l #{width} -t #{session_name}:#{window_name}.0 bosh ssh #{vm['job']}/#{vm['index']}`
  `tmux send-keys -t #{session_name}:#{window_name}.1 "sudo watch -n 1 /var/vcap/bosh/bin/monit summary" C-m`
end

# client.switch(session_name)
`tmux switch-client -t #{session_name}`
